#define BaseIconID 78000

class Life_HUD_nameTags {
    idd = -1;
    duration = 1e+011;
    name = "Life_HUD_nameTags";
    onLoad = "uiNamespace setVariable ['Life_HUD_nameTags',_this select 0]";
    objects[] = {};

    class controls
    {
        class BaseIcon
        {
            idc = -1;
            type = 13;
            style = 0;
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            font = "PuristaMedium";
            text = "";
            size = 0.04;
            shadow = 1.5;
            w = 0; h = 0;
            x = 0.1; y = 0.1;
        };

        class p1 : BaseIcon {idc = BaseIconID;};
        class p2 : BaseIcon {idc = BaseIconID + 1;};
        class p3 : BaseIcon {idc = BaseIconID + 2;};
        class p4 : BaseIcon {idc = BaseIconID + 3;};
        class p5 : BaseIcon {idc = BaseIconID + 4;};
        class p6 : BaseIcon {idc = BaseIconID + 5;};
        class p7 : BaseIcon {idc = BaseIconID + 6;};
        class p8 : BaseIcon {idc = BaseIconID + 7;};
        class p9 : BaseIcon {idc = BaseIconID + 8;};
        class p10 : BaseIcon {idc = BaseIconID + 9;};
        class p11 : BaseIcon {idc = BaseIconID + 10;};
        class p12 : BaseIcon {idc = BaseIconID + 11;};
        class p13 : BaseIcon {idc = BaseIconID + 12;};
        class p14 : BaseIcon {idc = BaseIconID + 13;};
        class p15 : BaseIcon {idc = BaseIconID + 14;};
        class p16 : BaseIcon {idc = BaseIconID + 15;};
        class p17 : BaseIcon {idc = BaseIconID + 16;};
        class p18 : BaseIcon {idc = BaseIconID + 17;};
        class p19 : BaseIcon {idc = BaseIconID + 18;};
        class p20 : BaseIcon {idc = BaseIconID + 19;};
        class p21 : BaseIcon {idc = BaseIconID + 20;};
        class p22 : BaseIcon {idc = BaseIconID + 21;};
        class p23 : BaseIcon {idc = BaseIconID + 22;};
        class p24 : BaseIcon {idc = BaseIconID + 23;};
        class p25 : BaseIcon {idc = BaseIconID + 24;};
        class p26 : BaseIcon {idc = BaseIconID + 25;};
        class p27 : BaseIcon {idc = BaseIconID + 26;};
        class p28 : BaseIcon {idc = BaseIconID + 27;};
        class p29 : BaseIcon {idc = BaseIconID + 28;};
        class p30 : BaseIcon {idc = BaseIconID + 29;};
        class p31 : BaseIcon {idc = BaseIconID + 30;};
        class p32 : BaseIcon {idc = BaseIconID + 31;};
        class p33 : BaseIcon {idc = BaseIconID + 32;};
        class p34 : BaseIcon {idc = BaseIconID + 33;};
        class p35 : BaseIcon {idc = BaseIconID + 34;};
        class p36 : BaseIcon {idc = BaseIconID + 35;};
        class p37 : BaseIcon {idc = BaseIconID + 36;};
        class p38 : BaseIcon {idc = BaseIconID + 37;};
        class p39 : BaseIcon {idc = BaseIconID + 38;};
        class p40 : BaseIcon {idc = BaseIconID + 39;};
        class p41 : BaseIcon {idc = BaseIconID + 40;};
        class p42 : BaseIcon {idc = BaseIconID + 41;};
        class p43 : BaseIcon {idc = BaseIconID + 42;};
        class p44 : BaseIcon {idc = BaseIconID + 43;};
        class p45 : BaseIcon {idc = BaseIconID + 44;};
        class p46 : BaseIcon {idc = BaseIconID + 45;};
        class p47 : BaseIcon {idc = BaseIconID + 46;};
        class p48 : BaseIcon {idc = BaseIconID + 47;};
        class p49 : BaseIcon {idc = BaseIconID + 48;};
        class p50 : BaseIcon {idc = BaseIconID + 49;};
        class p51 : BaseIcon {idc = BaseIconID + 50;};
        class p52 : BaseIcon {idc = BaseIconID + 51;};
        class p53 : BaseIcon {idc = BaseIconID + 52;};
        class p54 : BaseIcon {idc = BaseIconID + 53;};
        class p55 : BaseIcon {idc = BaseIconID + 54;};
        class p56 : BaseIcon {idc = BaseIconID + 55;};
        class p57 : BaseIcon {idc = BaseIconID + 56;};
        class p58 : BaseIcon {idc = BaseIconID + 57;};
        class p59 : BaseIcon {idc = BaseIconID + 58;};
        class p60 : BaseIcon {idc = BaseIconID + 59;};
        class p61 : BaseIcon {idc = BaseIconID + 60;};
        class p62 : BaseIcon {idc = BaseIconID + 61;};
        class p63 : BaseIcon {idc = BaseIconID + 62;};
        class p64 : BaseIcon {idc = BaseIconID + 63;};
        class p65 : BaseIcon {idc = BaseIconID + 64;};
        class p66 : BaseIcon {idc = BaseIconID + 65;};
        class p67 : BaseIcon {idc = BaseIconID + 66;};
        class p68 : BaseIcon {idc = BaseIconID + 67;};
        class p69 : BaseIcon {idc = BaseIconID + 68;};
        class p70 : BaseIcon {idc = BaseIconID + 69;};
        class p71 : BaseIcon {idc = BaseIconID + 70;};
        class p72 : BaseIcon {idc = BaseIconID + 71;};
        class p73 : BaseIcon {idc = BaseIconID + 72;};
        class p74 : BaseIcon {idc = BaseIconID + 73;};
        class p75 : BaseIcon {idc = BaseIconID + 74;};
        class p76 : BaseIcon {idc = BaseIconID + 75;};
        class p77 : BaseIcon {idc = BaseIconID + 76;};
        class p78 : BaseIcon {idc = BaseIconID + 77;};
        class p79 : BaseIcon {idc = BaseIconID + 78;};
        class p80 : BaseIcon {idc = BaseIconID + 79;};
        class p81 : BaseIcon {idc = BaseIconID + 80;};
        class p82 : BaseIcon {idc = BaseIconID + 81;};
        class p83 : BaseIcon {idc = BaseIconID + 82;};
        class p84 : BaseIcon {idc = BaseIconID + 83;};
        class p85 : BaseIcon {idc = BaseIconID + 84;};
        class p86 : BaseIcon {idc = BaseIconID + 85;};
        class p87 : BaseIcon {idc = BaseIconID + 86;};
        class p88 : BaseIcon {idc = BaseIconID + 87;};
        class p89 : BaseIcon {idc = BaseIconID + 88;};
        class p90 : BaseIcon {idc = BaseIconID + 89;};
        class p91 : BaseIcon {idc = BaseIconID + 90;};
        class p92 : BaseIcon {idc = BaseIconID + 91;};
        class p93 : BaseIcon {idc = BaseIconID + 92;};
        class p94 : BaseIcon {idc = BaseIconID + 93;};
        class p95 : BaseIcon {idc = BaseIconID + 94;};
        class p96 : BaseIcon {idc = BaseIconID + 95;};
        class p97 : BaseIcon {idc = BaseIconID + 96;};
        class p98 : BaseIcon {idc = BaseIconID + 97;};
        class p99 : BaseIcon {idc = BaseIconID + 98;};
        class p100 : BaseIcon {idc = BaseIconID + 99;};
        class p101 : BaseIcon {idc = BaseIconID + 100;};
        class p102 : BaseIcon {idc = BaseIconID + 101;};
        class p103 : BaseIcon {idc = BaseIconID + 102;};
        class p104 : BaseIcon {idc = BaseIconID + 103;};
        class p105 : BaseIcon {idc = BaseIconID + 104;};
        class p106 : BaseIcon {idc = BaseIconID + 105;};
        class p107 : BaseIcon {idc = BaseIconID + 106;};
        class p108 : BaseIcon {idc = BaseIconID + 107;};
        class p109 : BaseIcon {idc = BaseIconID + 108;};
        class p110 : BaseIcon {idc = BaseIconID + 109;};
    };
};