/*
	Master UI Resource File
*/
#include "common.hpp"
#include "shop_items.hpp"
#include "gang.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "hud_stats.hpp"
#include "admin_menu.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.hpp"
#include "pInteraction.hpp"
#include "deathScreen.hpp"
#include "vehicleShop.hpp"
#include "settings.hpp"
#include "federalReserve.hpp"
#include "compensate.hpp"
#include "FuelStat.hpp"
#include "AltisPhone.hpp"
//Travis's Custom Phone
#include "CustomPhone\Dialog\player_inv.hpp"
#include "CustomPhone\Dialog\player_menu.hpp"
#include "CustomPhone\Dialog\key_chain.hpp"
#include "CustomPhone\Dialog\moves_menu.hpp"
#include "CustomPhone\Dialog\cell_phone.hpp"
#include "CustomPhone\Dialog\TR8_Banking.hpp"
#include "CustomPhone\Dialog\TR8_Licences.hpp"
